# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '40 20 * * *' # once a day at 20:40 UTC / 12:40 PST
    
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_2:
       runs-on: self-hosted
       steps: 

      # Runs a single command using the runners shell
          - name: Run a new cmd
            run: |
                sudo modprobe virtio-lo
                sudo modprobe virtio_gpu
                
                rvgpu-renderer -b 1280x720@0,0 -p 55667 &
                
                sudo su
                export XDG_RUNTIME_DIR=/run/user/0
                rvgpu-proxy -l 0 -s 1280x720@0,0 -n 127.0.0.1:55667 &
                export LD_LIBRARY_PATH=/usr/lib/mesa-virtio
                weston --backend drm-backend.so --tty=2 --seat=seat_virtual -i 0 --log=/tmp/weston.log &
                
                glmark2-es2-wayland
            


